# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Skillbox Disk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skillbox Disk
  pod 'SnapKit', '~> 5.0.0'
  pod 'KeychainSwift', '~> 20.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'Charts'

end
